[package]
name = "smbanything"
version = "0.0.2"
edition = "2024"

[workspace]
members = ["smbanything_core"]
resolver = "3"

[dependencies]
anyhow = "1"
bytes = "1"
clap = { version = "4.5", features = ["derive"] }
ctrlc = { version = "3.5", features = ["termination"] }
sha2 = "0.11"
smbanything_core = { path = "smbanything_core" }
tar = "0.4"
tempfile = "3"
zip = { version = "8.6", default-features = false, features = [
    "bzip2",
    "deflate64",
    "deflate-flate2-zlib-rs",
    "legacy-zip",
    "lzma",
    "ppmd",
    "xz",
    "zstd",
] }
